### ISSUE TITLE
add support for serde for tokens

### ISSUE THREAD

**Issue by kstep** [programble/inth-oauth2#2]
It would be nice if tokens (`token::Bearer`) could be serialized/deserialized with serde as well as rustc_serialize. Thank you!

**Comment by programble** [comment]
I really don't like the amount of weird setup required to get Serde derives working on stable, but I may take a stab at implementing the needed traits manually, since that is actually documented for Serde, unlike rustc_serialize.

**Comment by programble** [comment]
Released in v0.6.0.
